### PR TITLE
NCL-4632 Replace commons-configuration with OWNER 

### PR DESCRIPTION
**Pull request by rnc**
Draft for early feedback. Note - need the manipulation functional tests fixing - discussing with @metacosm what the test is meant to be doing).

### CODE REVIEW

**Comment by metacosm** [comment]
#29 brings the modification of the tests we talked about that removes the need to bypass the dependencies override to make the test pass.

**Comment by rnc** [comment]
@metacosm Ah damn, I've just done the same as well!

**Comment by metacosm** [comment]
@rnc  you need to do the same for the multi-module test as well and remove the bypass property set: https://github.com/project-ncl/gradle-manipulator/blob/master/manipulation/build.gradle.kts#L40

**Comment by rnc** [comment]
@metacosm I've cherry-picked your commit onto this branch :-) Thanks!

**Comment by rnc** [comment]
I think this is ready for review now. I'd rather it was merged than squashed and merged to preserve the commits.

**Pull request merged**
