### PR TITLE
NCL-4726 Export artifact repository settings

### PR DESCRIPTION
**Pull request by TomasHofman**
https://projects.engineering.redhat.com/browse/NCL-4726

This should probably wait until after the first release.

Functionality:

If `-DrepoRemovalBackup=path/to/settings.xml` property is configured, `settings.xml` file will be generated and will contain remote repositories used by the project. This file will be picked by PNC in order to automatically configure repository proxying. (I hope I got this right, that is what PME does.)

The property name `repoRemovalBackup` is the same as in PME (respectively PME is accepting two variants, camel case or dashed).

### CODE REVIEW

**Comment by geoand** [comment]
Cool! I can't really comment since I don't have the PME experience, but this looks neat

**Comment by TomasHofman** [comment]
Cc @rnc when you have time, not urgent...

**Comment by rnc** [comment]
+1 thanks for implementing that idea.

cc @vibe13 @thescouser89  -  this should help and also potentially reduce any work @pkocandr has to do.

**Comment by rnc** [comment]
@TomasHofman Can we also get some updates for the documentation please? (on the gh-pages branch)

**Pull request merged**
