### PR TITLE
NCL-5886 Fix for testing on later Gradle versions : update to use newer API for dependencies, update functionalTest to correctly obtain plugin test metadata, remove ca.cutterslade.analyze plugin. Update Travis to test on later Gradle versions.

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by rnc** [comment]
Fix for https://github.com/gradle/gradle/issues/15269

**Comment by rnc** [comment]
@geoand You might be interested in this and the linked Gradle bug report ; it appears the `INDEX.LIST` (which is standard if `jboss-parent` is used) can cause problems with Gradle TestKit

**Comment by geoand** [comment]
WOW! That is so weird!

Amazing detective work BTW!

**Comment by rnc** [comment]
Holding merging this until I release a new PME 4.2 (and can update this PR ; it is currently verified using 4.2-SNAPSHOT)

**Pull request merged**
